Improve Makefile (install, uninstall)
lcn2/dyn_array pull request #6
Opened 2024-09-01 18:35 UTC by xexyl

Add PREFIX variable to Makefile to allow for installing to a different location than the default /usr/local.

Add uninstall rule.

To be congruent with the install rule the uninstall rule has a way to silence the -v option to rm as well (instead of the install command).

Updated README.md. I note that the structure of the file could be improved upon but I do not have time for this right now.

2024-09-01 22:21 UTC, lcn2 requested changes
See [GHpullrequestreview-2274502376-](https://github.com/lcn2/dyn_array/pull/6#pullrequestreview-2274502376).

2024-09-01 23:03 UTC, lcn2 requested changes
# QUESTION 

Should instances of `/usr/local` in the `make depend` rule become `${PREFIX}` ?    You might wish to modify the `make depend` llne from:

```make
        ${SED} -E -e 's;\s/usr/local/include/\S+;;g' -e 's;\s/usr/include/\S+;;g' | \
```

to:

```make
        ${SED} -E -e 's;\s${PREFIX}/include/\S+;;g' -e 's;\s/usr/include/\S+;;g' | \
```

BTW: It is OK if "_PREFIX == /usr_" as the 2nd sed expression would just become redundant.  And if "_PREFIX != /usr_" then the 2nd `/usr/include` related sed expression is still needed to address default system includes.

## UPDATE 0

Please also consider [GH-pullrequestreview-2274499706](https://github.com/ioccc-src/mkiocccentry/pull/953#pullrequestreview-2274499706).  We will hold off in processing this PR so that you may more easily update and test the combined set of 3 PRs across the 3 impacted repos.

## UPDATE 1

Overall we like the concept you have introduced, @xexyl.  With the above suggested modifications as well as solving the check failure issues, the modified PR will be a welcome addition.

2024-09-02 00:02 UTC, xexyl commented
As noted in the others I will take care of this tomorrow morning. 

Have a great rest of your day!

2024-09-02 13:51 UTC, xexyl commented
I don't think the make depend should be or needs to be modified. The `${CC}` doesn't need or use the `${PREFIX}` and macOS does not add with `-MM` the directory `/usr/include` either. Given the problems in the mkiocccentry Makefile that I mentioned (the `LD_SPECIAL` does not work as you hoped and the `C_SPECIAL` variable is also not what you hoped if more than one option has to be specified) perhaps this could be merged and you can then play with this more? This way at least the `PREFIX` functionality is there. But since you want to process all three at the same time and since that one won't work as you hoped ...

Updating the depend rule to include `PREFIX` does nothing because:

```sh
mkdir foo ; cp dbg.h foo/
make PREFIX=foo depend
```

what then? The `Makefile` won't change as it stands. This is because the compiler does not have the include directories updated since the depend rule uses:

```makefile
${CC} ${CFLAGS} -MM -I. ${ALL_CSRC}
```

and the `${CFLAGS}` does not include `PREFIX`. 

Please advise how you wish me to proceed or if you want you can merge this and then play with it.

2024-09-02 16:32 UTC, lcn2 commented
We will process these PRs as is and then we will fix, if and as needed afterwards.

2024-09-02 16:32 UTC, merged

2024-09-02 19:46 UTC, xexyl commented
> We will process these PRs as is and then we will fix, if and as needed afterwards.

Thanks.